### ISSUE TITLE
License

### ISSUE THREAD

**Issue by brandon-gallas** [stanfordmlgroup/lca-code#1]
Nice work. Please put a LICENSE.md file in the root directory so that your sharing intentions are clear. We are doing research that may draw on your data and analysis scripts of reader performance.

Brandon D. Gallas, PhD
Mathematician
Division of Imaging, Diagnostics, and Software Reliability (DIDSR) 
Office of Science and Engineering Laboratories (OSEL) 
Center for Devices and Radiological Health (CDRH) 
10903 New Hampshire Ave, WO-62 Rm 4104, Silver Spring, MD 20993
Email: brandon.gallas@fda.hhs.gov
Phone: 301-796-2531

**Comment by akiani** [comment]
Done. Thanks for your interest.
